name: statefulclickcounter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  fluttertoast: ^8.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  firebase_database: ^10.4.6
  js: ^0.6.2
  intl: ^0.18.1
  file_picker: ^6.1.1
  lottie: ^3.1.0 # Add this line
  firebase_storage: ^11.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # If you want to add fonts in the future:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
